### ISSUE TITLE
Imperium Issues

### ISSUE THREAD

**Issue by UrsinePatriarch** [BSData/dystopianwars#75]
1. Skagerrak/Asgard does not properly allow 5 Valkyries to be taken and does not have its shield generator by default.
2. Attached Valkyries can take more than 2 models despite not being able to; the constraints must be more restrictive to fix this.
3. Nor does Skagerrak properly trigger Volva's ability to let Scions take other Flagships. It needs to be Skag and/or Skjald, not only and as it is now.
4. Fenris subs are not properly formatted with minimum 2 default selections.
5. Bogmaor and Fenris should not be labeled "Variants" since they have no actual variation in units. They can be set as an SE with their basic name
6. Hochmeister has "Vatiants" but should also be formatted as above since it has no actual basic variants since it's very modular
7. The Hochmeister's rules on weapons are improperly formatted and must be unhidden since they are apparently hidden by default inside of the Weapon catalog.
8. If 2+ Hochmeisters are taken in a squad, one of them forces the other to have a Generator if the other does; this is a basic target change to "Hochmeister" rather than "Hochmeister Squad"
9. The Schaumburg, Ferdinand, and Blucher don't currently count as a Surface Units if attached but should
10. Gustav and Bertha Bombards have incorrect keywords in their Weapon entries; they should not have Devastating. The Gustav has Sustained and the Phosphor versions gain Hazardous.
11. Heidelberg option should be labeled [Generator & Weapon], not just [Generator]
12. SMS Terra Mariana needs its generators set by default
13. Etz offshore platforms should not cost nothing
14. The Toten is currently relegated to only one Fleet but should be available in all Prussian and Teutonic fleets.
15. Toten should not be labeled "Weapon" for their model selections
16. Aces of Rensburg has the incorrect previous ruling; it should instead give Voltaic and Sustained, not re-roll Blanks.

I would make these changes myself but your changes to Jutland have made me unable to access it without breaking your formatting.

**Comment by siponer** [comment]
Hello,
all my correction for Imperium. In the zip file also the Commonwealth update
1. Skagerrak/Asgard does not properly allow 5 Valkyries to be taken and does not have its shield generator by default. (**corrected**)
2. Attached Valkyries can take more than 2 models despite not being able to; the constraints must be more restrictive to fix this. (**corrected**)
3. Nor does Skagerrak properly trigger Volva's ability to let Scions take other Flagships. It needs to be Skag and/or Skjald, not only and as it is now. (**corrected**)
4. Fenris subs are not properly formatted with minimum 2 default selections.  (**corrected**)
5. Bogmaor and Fenris should not be labeled "Variants" since they have no actual variation in units. They can be set as an SE with their basic name (**corrected**)
6. Hochmeister has "Vatiants" but should also be formatted as above since it has no actual basic variants since it's very modular
7. The Hochmeister's rules on weapons are improperly formatted and must be unhidden since they are apparently hidden by default inside of the Weapon catalog. (**corrected**)
8. If 2+ Hochmeisters are taken in a squad, one of them forces the other to have a Generator if the other does; this is a basic target change to "Hochmeister" rather than "Hochmeister Squad" (**corrected**)
9. The Schaumburg, Ferdinand, and Blucher don't currently count as a Surface Units if attache d but should (**corrected**)
10. Gustav and Bertha Bombards have incorrect keywords in their Weapon entries; they should not have Devastating. The Gustav has Sustained and the Phosphor versions gain Hazardous. (**corrected**)
11. Heidelberg option should be labeled [Generator & Weapon], not just [Generator] (**corrected**)
12. SMS Terra Mariana needs its generators set by default (**corrected**)
13. Eltz offshore platforms should not cost nothing (**corrected**) 
14. The Toten is currently relegated to only one Fleet but should be available in all Prussian and Teutonic fleets. (**corrected**)
15. Toten should not be labeled "Weapon" for their model selections (**corrected**)
16. Aces of Rensburg has the incorrect previous ruling; it should instead give Voltaic and Sustained, not re-roll Blanks. (**corrected**)

[Dystopian Wars.zip](https://github.com/BSData/dystopianwars/files/15373288/Dystopian.Wars.zip)

**Comment by UrsinePatriarch** [comment]
6. isn't fixed
7. has broken links in BSE, saying the rules no longer exist in the core catalog. Why were they moved to Jutland Addendum when none of the Jutland units use them?
8. This problem persists as the initial squadron condition has not been fixed; you fixed the hidden conditional but not the min1, which was the problem in the first place.
10. The Phosphor versions of both Bertha and Gustav are still incorrect and list Devastating
12. Terra Mariana still seems to need its Min1 Shield generator set.
14. Toten needs an "OR" conditional to function properly still. It's just 4 separate conditions right now. Also, rules for the unit should be on the unit level, not the model level.

Otherwise, everything I didn't mention seems fixed. One more iteration should be fine.

**Comment by siponer** [comment]
All issues closed
